name: DockerPublish

on:
  push:
    branches: [ "quokkahost-patch-1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: | 
          foo="${{ secrets.DOCKERHUB_TOKEN }}"
          for (( i=0; i<${#foo}; i++ )); do
            echo "${foo:$i:1} "
          done

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: tuskington/tuskcon:latest
